### ISSUE TITLE
Errors in google_home_resume.yaml

### ISSUE THREAD

**Issue by Kagey-cmd** [TheFes/Google-Home-Resume#2]
Is it normal for there to be errors (flagged by VS Code) in the google_home_resume.yaml file?
Specifically:

-697-                  data: "{{ data }}"                 <<Incorrect type. Expected "Object".

And a few other similar.
I can provide more details if needed.

**Comment by TheFes** [comment]
Yes, that's normal.
VSCode expects a mapping there, but I provide that in a template, which it doesn't expect.
You can ignore it.
