### ISSUE TITLE
Soptify playlist not resumed

### ISSUE THREAD

**Issue by t-abraham** [TheFes/Google-Home-Resume#3]
Hi, firstly thanks a lot for the great effort in the scripts. It works greats but i found out that after google home speaker is interrupted by event and resumed, it just plays that song a s short period (around 30 seconds). Also if the song was almost at the last end (less than 30 seconds) then it completes the song but doe not move to the next song of the playlist. Any idea why this happens?

**Comment by TheFes** [comment]
Not sure why that is, but Spotify resume is handled by Spotcast. The script just uses the Spotcast service call.

Is there anything in your logbook which shows why it stopped?

**Comment by t-abraham** [comment]
unfortunately nothing... it shows that the automation triggered took the current playing info and then streamed a media from local and then again resumed the current playing info. Then after few minutes the speaker turned off automatically :(

**Comment by TheFes** [comment]
but that last step (the turning off) isn't shown in the logbook at all? Or it just doesn't show why it is turned off?

**Comment by t-abraham** [comment]
i doesnt not show why it is turned off

**Comment by TheFes** [comment]
Then it's stopped for a reason outside Home Assistant and HA only registered and logged the state change.

Does the same thing happen if you use the `spotcast.start` service call in developer tools > services?

**Comment by t-abraham** [comment]
Sorry for the late response... I have checked two time with direct service call. One time it ran great for 1 hour and then I manually stopped and then the other time it got stopped after around 7-10 mins

**Comment by t-abraham** [comment]
I found out the issue its with Spotify and 3rd party speakers other than google nest
