### ISSUE TITLE
Script sometimes not resuming

### ISSUE THREAD

**Issue by Jaykurb** [TheFes/Google-Home-Resume#7]
Sometimes, the script does not resume as expected. I notice this happens when I use an automation that involves looping. Could you please take a look at this when you get a chance to see what is causing the issue?

[Google Home Resume - Helper Script](https://pastebin.com/9MuZL24F)
[Google Home Resume](https://pastebin.com/ktkkSNek)

**Comment by TheFes** [comment]
Hi,

Not much I can see from these traces, as the player data indicates there wasn't anything to resume.
What do you exaclty mean with looping? Are you sending this message every x minutes?

**Comment by Jaykurb** [comment]
> Hi,
> 
> 
> 
> Not much I can see from these traces, as the player data indicates there wasn't anything to resume.
> 
> What do you exaclty mean with looping? Are you sending this message every x minutes?

Hi, yes so some automations will loop every x mins until a Boolean is switched off. 

Most of the time it works fine but sometimes it just plays the Google start tone and fails to play the TTS. When this does happen the only way to resolve is by restarting HA.

**Comment by TheFes** [comment]
You should be able to just stop the script (if it is indeed somehow blocking everything).
There is a max number of runs on the script, so at one point it won't run anymore.
