### ISSUE TITLE
Not annoucing, no errors

### ISSUE THREAD

**Issue by jckickflip** [TheFes/Google-Home-Resume#9]
I'm trying to use this script to resume spotify music after announcement and it seems to be working except on the google hubs, they stop and bring up the tts screen but do not actually say anything and they they resume the music.
I have attached the automation (just using Jesse for testing), The trace for the resume script and also the script for the resume helper script. Does not seem to have any errors.
https://www.dpaste.org/oLrF4
https://www.dpaste.org/pRg3g
https://www.dpaste.org/RWAPn

**Comment by jckickflip** [comment]
Yeah that is what it seemed like to me to and I even tried adding a wait for 10 seconds after the tts, no change.

**Comment by TheFes** [comment]
And just to be clear, you only have this on the hubs, on the others (non screen) speakers it does work?

**Comment by jckickflip** [comment]
No after checking around the house it is happening on the minis also

**Comment by jckickflip** [comment]
The living room display seems to be the only one that consistently works

**Comment by jckickflip** [comment]
I have been playing with this for the past 3 days trying to get it to work. I have tried calling each individual entity instead of the group and they will each talk but not resume, I also tried using the event scrip to save each status before the tts then restore each speaker after the tts, and it still does not resume. Not really sure what else I can try and I’m not sure I don’t have something wrong in settings or just not implementing the scripts correctly. Do you have any ideas I can try or tests I can run?

**Comment by TheFes** [comment]
I will have a look after the weekend

**Comment by sorano** [comment]
Any update on this?

I setup this sometime during last year and it was working then. Somewhere along the way it broke and I didn't bother look into it until today.

What happens is that any device will stop music and play the TTS message, but never resume Spotify.

**Comment by TheFes** [comment]
Sorry, I've been quite busy with work, and your dpaste links expired now. Can you send new traces.
Please make sure to use traces from when it didn't work properly.

**Comment by TheFes** [comment]
Could you check if https://github.com/TheFes/Google-Home-Resume/releases/tag/2024.8.0 fixes it for you? Otherwise please send traces using that version.

**Comment by TheFes** [comment]
closed because of lack of resonse in the last 3 months
